version: '3.8'

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: ${DATABASE_URL}
      DB_NAME: ${MONGO_DB}
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    restart: always


  ghi:
    build:
      context: ghi
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
